# Generated by Django 4.2.5 on 2023-10-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusDefinition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status_definition", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "recipient",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("project_name", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.statusdefinition",
                    ),
                ),
            ],
        ),
    ]
