# Generated by Django 4.2.5 on 2023-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusdefinition",
            name="status_description",
            field=models.TextField(default="Not specified"),
        ),
    ]
